#file: noinspection SpringBootApplicationYaml
server:
  port: 8081
spring:
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        model: gemma3:4b-it-q4_K_M
        request-options:
          timeout: 300s
      base-url: "http://localhost:11431"