#file: noinspection SpringBootApplicationYaml
server:
  port: 8081

cache:
  resumeDir: "test/resume"

mail:
  gmail:
    enabled: ${GMAIL_ENABLED:true}
    secret: ${GMAIL_SECRET}
  yandex:
    enabled: ${YANDEX_ENABLED:true}
  mock:
    enabled: ${MOCK_ENABLED:true}
  imap:
    host: imap.yandex.com
    port: 993
    username: ${YA_LOGIN}
    password: ${YA_PWD}  # пароль приложения!
    inbox-folder: Vacancy
    polling-interval-ms: 10000  # каждые 10 секунд

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  flyway:
    baseline-description: true
    baseline-on-migrate: true
    create-schemas: true
    default-schema: public
    enabled: true
    locations: classpath:db/migration
    schemas: public
    url: jdbc:postgresql://localhost:5432/ragdb
    user: postgres
    password: postgres
    validate-on-migrate: true